import type { Metadata } from "next";
import { Share_Tech, Jost } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/sections/ThemeContext";
import { PageBackground } from "@/components/sections/PageBackground";

const shareTech = Share_Tech({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-navbar',
});

const jost = Jost({
  subsets: ['latin'],
  variable: '--font-body',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full antialiased", shareTech.variable, jost.variable)}
    >
      <body className={cn("min-h-full flex flex-col", jost.className)}>
        <ThemeProvider>
          <PageBackground />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}